export const UPDATE_WH_IN_SUCCESS = 'UPDATE_WH_IN_SUCCESS'
export const UPDATE_WH_IN_FAILED = 'UPDATE_WH_IN_FAILED'
export const UPDATE_WH_IN_ERROR = 'UPDATE_WH_IN_ERROR'

export const GET_DETAIL_INCOMING_ITEMS_SUCCESS = 'GET_DETAIL_INCOMING_ITEMS_SUCCESS'
export const GET_DETAIL_INCOMING_ITEMS_FAILED = 'GET_DETAIL_INCOMING_ITEMS_FAILED'
export const GET_DETAIL_INCOMING_ITEMS_ERROR= 'GET_DETAIL_INCOMING_ITEMS_ERROR'

export const GET_INCOMING_ITEMS_SUCCESS = 'GET_INCOMING_ITEMS_SUCCESS'
export const GET_INCOMING_ITEMS_FAILED = 'GET_INCOMING_ITEMS_FAILED'
export const GET_INCOMING_ITEMS_ERROR= 'GET_INCOMING_ITEMS_ERROR'

export const GET_OUTGOING_ITEMS_SUCCESS = 'GET_OUTGOING_ITEMS_SUCCESS'
export const GET_OUTGOING_ITEMS_FAILED = 'GET_OUTGOING_ITEMS_FAILED'
export const GET_OUTGOING_ITEMS_ERROR= 'GET_OUTGOING_ITEMS_ERROR'

export const UPDATE_WH_OUT_SUCCESS = 'UPDATE_WH_OUT_SUCCESS'
export const UPDATE_WH_OUT_FAILED = 'UPDATE_WH_OUT_FAILED'
export const UPDATE_WH_OUT_ERROR = 'UPDATE_WH_OUT_ERROR'

export const LOGIN_SUCCESS      = 'LOGIN_SUCCESS'
export const LOGIN_FAILED       = 'LOGIN_FAILED'
export const LOGIN_ERROR        = 'LOGIN_ERROR'
export const REFRESH            = 'REFRESH'